export default function OurStory() {
    return <div className="w-full h-20 bg-transparent sticky top-0 text-red-500">
        <div className="container mx-auto px-4 h-full">
          <h1 className="border-b-2 border-red-400 m-5 text-lg font-custom1">
            💗 our story 
          </h1>
          <p className="font-custom1">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas venenatis nibh vitae massa feugiat, ut egestas quam malesuada. Maecenas iaculis imperdiet tortor a semper. Nullam sit amet velit elementum, suscipit metus quis, pretium justo. Vivamus in tortor in leo porta iaculis. Proin id ligula commodo elit tincidunt lobortis. Cras varius dapibus augue, quis laoreet nisl. Aliquam elementum, felis sit amet facilisis fringilla, enim ex efficitur nibh, non interdum massa velit laoreet lectus.
          Maecenas finibus laoreet urna in venenatis. Maecenas a suscipit nisi. Maecenas faucibus erat ut metus elementum aliquet. Donec et lobortis erat. Curabitur iaculis libero sit amet posuere pharetra. Quisque vestibulum accumsan purus et tincidunt. Maecenas non erat felis. Quisque quis quam id dui pulvinar tincidunt eu at metus.
          Nuncu viverra arcu. Vestibulum feugiat mauris non luctus facilisis. Proin hendrerit elit sit amet velit eleifend lobortis. Mauris euismod blandit felis blandit cursus. Nulla euismod lectus tempor diam hendrerit sollicitudin faucibus quis odio. Praesent turpis quam, consequat sit amet urna non, pulvinar scelerisque augue. Morbi mollis purus egestas tincidunt sollicitudin. In malesuada nisi vel turpis vestibulum lacinia eu id dolor. Aliquam erat volutpat. Aliquam scelerisque, quam at vulputate vestibulum, quam quam aliquet augue, ut vulputate nisl ante sit amet arcu. Nam cursus velit odio. Nam volutpat semper risus a lobortis.
          Maecenas in placerat elit. Sed egestas malesuada lorem. Aenean molestie pellentesque hendrerit. Vivamus porta malesuada congue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed maximus arcu nisi, id consequat erat ultricies vitae. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris vel tempus risus, at tincidunt elit. Proin vitae mi auctor, luctus sapien vitae, blandit ligula.
          aeas gravida diam nec arcu laoreet ultrices. Integer molestie nec tellus eget pretium. Duis laoreet velit in malesuada convallis. Duis in tempor tellus. Integer ullamcorper dolor at sollicitudin venenatis. Nullam mollis purus eu lectus aliquam, nec pellentesque felis viverra. Nunc ut lorem vitae libero interdum vestibulum. Etiam congue eros eu eros volutpat, ac mollis justo elementum. Integer at sollicitudin nisi, at porttitor lacus. Integer lacinia sed lorem a euismod. Morbi et elementum nibh. Nam egestas commodo ligula, vel eleifend nulla malesuada nec. Morbi quis arcu dolor.
          </p>
        </div>
      </div>  }